FROM fn61/buildkit-golang:20180830_1321_5e3ef8bc40a3b5e4

WORKDIR /go/src/github.com/function61/pi-security-module

CMD bin/build.sh

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
	&& apt-get install -y nodejs mkdocs
