FROM golang:1.10.0

CMD bin/build.sh

WORKDIR /go/src/github.com/function61/pi-security-module

RUN curl --fail --location -o /go/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 \
	&& chmod +x /go/bin/dep \
	&& curl --location --fail -o /usr/local/bin/jfrog-cli "https://bintray.com/jfrog/jfrog-cli-go/download_file?file_path=1.12.1%2Fjfrog-cli-linux-amd64%2Fjfrog" \
	&& chmod +x /usr/local/bin/jfrog-cli
