FROM fn61/buildkit-golang:20181005_1708_d902a8e33c48a76f

WORKDIR /go/src/github.com/function61/pi-security-module

CMD bin/build.sh

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
	&& apt-get install -y nodejs mkdocs
